services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=discussnewsdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - discussnews-network
    ports:
      - "5432:5432"

networks:
  discussnews-network:
    driver: bridge

volumes:
  postgres-data:
